I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 31, in script
    $ povname = renpy.input("What is your name?")
  File "game/script.rpy", line 31, in <module>
    $ povname = renpy.input("What is your name?")
  File "game/custom_screens.rpy", line 12, in execute
    screen StatsUI:
  File "game/custom_screens.rpy", line 12, in execute
    screen StatsUI:
  File "game/custom_screens.rpy", line 14, in execute
    frame:
NameError: name 'knowledge' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 31, in script
    $ povname = renpy.input("What is your name?")
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 31, in <module>
    $ povname = renpy.input("What is your name?")
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/exports/inputexports.py", line 177, in input
    rv = renpy.ui.interact(mouse='prompt', type="input", roll_forward=roll_forward)
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/display/core.py", line 2218, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/display/core.py", line 2748, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/display/displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/display/displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/display/displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/display/screen.py", line 480, in visit_all
    callback(self)
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/display/core.py", line 2748, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/display/screen.py", line 491, in per_interact
    self.update()
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/display/screen.py", line 700, in update
    self.screen.function(**self.scope)
  File "game/custom_screens.rpy", line 12, in execute
    screen StatsUI:
  File "game/custom_screens.rpy", line 12, in execute
    screen StatsUI:
  File "game/custom_screens.rpy", line 14, in execute
    frame:
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/text/text.py", line 2177, in _scope
    return self.set_text(self.text_parameter, scope, self.substitute, update)
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/text/text.py", line 2216, in set_text
    i, did_sub = renpy.substitutions.substitute(i, scope, substitute) # type: ignore
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/substitutions.py", line 373, in substitute
    s = interpolate(s, variables) # type: ignore
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/substitutions.py", line 86, in interpolate
    raise e
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
NameError: name 'knowledge' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Cadence of Love 1.0
Sat Apr 19 22:08:37 2025
